"""create users profiles and settings

Revision ID: ab04af09e7df
Revises:
Create Date: 2026-08-04 23:57:27.082088

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab04af09e7df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(btrim(email))", name=op.f("ck_users_email_normalized")),
        sa.CheckConstraint("length(email) > 3", name=op.f("ck_users_email_minimum_length")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("sex_for_formula", sa.String(length=10), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("goal", sa.String(length=30), nullable=True),
        sa.Column("activity_level", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_level IS NULL OR activity_level IN "
            "('sedentary', 'lightly_active', 'moderately_active', 'very_active')",
            name=op.f("ck_user_profiles_activity_level_allowed"),
        ),
        sa.CheckConstraint(
            "goal IS NULL OR goal IN ('weight_loss', 'maintain_weight', 'weight_gain')",
            name=op.f("ck_user_profiles_goal_allowed"),
        ),
        sa.CheckConstraint(
            "sex_for_formula IS NULL OR sex_for_formula IN ('male', 'female')",
            name=op.f("ck_user_profiles_sex_for_formula_allowed"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm BETWEEN 120.00 AND 230.00",
            name=op.f("ck_user_profiles_height_cm_range"),
        ),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg BETWEEN 35.00 AND 300.00",
            name=op.f("ck_user_profiles_weight_kg_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_user_profiles_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "measurement_system", sa.String(length=10), server_default="metric", nullable=False
        ),
        sa.Column("time_zone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "theme_preference", sa.String(length=10), server_default="system", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "measurement_system IN ('metric', 'imperial')",
            name=op.f("ck_user_settings_measurement_system_allowed"),
        ),
        sa.CheckConstraint(
            "theme_preference IN ('system', 'light', 'dark')",
            name=op.f("ck_user_settings_theme_preference_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_user_settings_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    op.drop_table("user_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
